# Generated by Django 3.1.1 on 2020-10-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tattoo',
            name='artist',
            field=models.CharField(default='whatever', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tattoo',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
